theme = "gruvbox-dark"
# icons = "awesome5"

[[block]]
block = "sound"
step_width = 3

# [[block]]
# block = "backlight"
# device = "intel_backlight"

[[block]]
block = "time"
format = "%H:%M"
timezone = "Europe/Amsterdam"
interval = 60
locale = "en_US"

[[block]]
block = "battery"
interval = 10
