#!/bin/sh

unset QT_STYLE_OVERRIDE
export _JAVA_AWT_WM_NONREPARENTING=1
export BEMENU_BACKEND=wayland
export CLUTTER_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1
export MOZ_WEBRENDER=1
export QT_QPA_PLATFORM=wayland-egl
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export SDL_VIDEODRIVER=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_DESKTOP_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

gsettings set $gnome-schema gtk-theme "Gruvbox-Material-Dark"
gsettings set $gnome-schema icon-theme "Papirus-Dark"
gsettings set $gnome-schema cursor-theme "Breeze_Snow"
gsettings set $gnome-schema font-name "Source Code Pro"

eval $(keychain --eval --quiet --noask --agents gpg,ssh id_rsa)

sway
