format = """
\\[$username$hostname: $directory\\] \
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

[directory]
style = "yellow"
format = '[$path]($style)[$read_only]($read_only_style)'

[directory.substitutions]

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "green"

[git_commit]
disabled = true

[git_status]
up_to_date = "✔"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "green"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
disabled = true
format = "[$duration]($style) "
style = "yellow"

[python]
disabled = true
format = "[$virtualenv]($style) "
style = "bright-black"

[username]
show_always = true
format = "[$user](blue)"

[hostname]
# ssh_only = false
format = "@[$hostname]($style)"
