format = """
([ $username$hostname ](bg:#3c3836)\
[ ](fg:#1d2021 bg:#3c3836))\
\
[ $directory ](bg:#3c3836)\
[([ ](fg:#1d2021 bg:#3c3836)\
$git_branch\
$git_commit\
$git_state\
$git_status )](fg:#8ec07c bg:#3c3836)\
\
[([ ](fg:#1d2021 bg:#3c3836)\
$elixir\
$custom\
$c\
$nodejs )](bg:#3c3836)\
\
[](#3c3836)\
$line_break\
$character
"""

continuation_prompt = ''

[character]
success_symbol = "[❯](#458588)"
error_symbol = "[❯](#cc241d)"
vimcmd_symbol = "[❮](green)"

[directory]
read_only = " 󰌾"
read_only_style = "fg:#fb4934 bg:#3c3836"
format = '$path[$read_only]($read_only_style)'

[git_branch]
symbol = "󰘬 "
style = "fg:#8ec07c bg:#3c3836"
format = "$symbol$branch"

[git_commit]
tag_symbol = " 󰓹 "
style = "fg:#8ec07c bg:#3c3836"
format = '[\($hash$tag\)]($style)'

[git_status]
format = "( $ahead_behind)( $all_status)"
stashed = ""
ahead = '[](fg:bold #689d6a bg:#3c3836)'
up_to_date = "[✔](fg:#689d6a bg:#3c3836)"
behind = '[](fg:bold #fb4934 bg:#3c3836)'
diverged = "[✘](fg:#fb4934 bg:#3c3836)"
staged = '[+](fg:bold #689d6a bg:#3c3836)'
deleted = '[-](fg:bold #fb4934 bg:#3c3836)'
untracked = '[?](fg:bold #fabd2f bg:#3c3836)'
renamed = '[»](fg:bold #fabd2f bg:#3c3836)'
modified = "[≠](fg:bold #fabd2f bg:#3c3836)"
typechanged = ''

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
disabled = true
format = "[$duration]($style) "
style = "yellow"

[username]
style_user = "fg:#83a598 bg:#3c3836"
style_root = "fg:bold #cc241d bg:#3c3836"
format = "[$user]($style)"
# show_always = true

[hostname]
# ssh_only = false
style = "fg:#fe8019 bg:#3c3836"
ssh_symbol = " "
format = "[@$hostname]($style)"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
style = 'fg:#fabd2f bg:#3c3836'
version_format = '${raw}'
format = '[$symbol($version(-$name))]($style)'

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
disabled = true
symbol = " "
style = 'fg:#d3869b04945'
version_format = '${raw}'
format = '[$symbol$version]($style)'

[custom.elixir]
symbol = " "
style = 'fg:#d3869b bg:#3c3836'
command = "$ASDF_DIR/shims/elixir --short-version"
format = '[$symbol$output]($style)'
# when = "test -f mix.exs"
detect_files = ['mix.exs']

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style = "fg:#98971a bg:#3c3836"
version_format = '${raw}'
format = '[$symbol($version)]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
