format = """
$username$hostname$directory \
(\\[$git_branch\
$git_state\
$git_status\\] )\
$elixir\
$custom\
$c\
$nodejs\
$jobs\
$line_break\
$character
"""

continuation_prompt = ''

[directory]
read_only = " 󰌾"
style = "yellow"
format = '[$path]($style)[$read_only]($read_only_style)'

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$branch]($style)"
style = "green"

[git_commit]
disabled = true

[git_status]
style = "green"
format = "[( $stashed)( $ahead_behind)[( $conflicted$untracked$modified$staged$renamed$deleted)](218)]($style)"
up_to_date = "✔"
modified = "≠"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
disabled = true
format = "[$duration]($style) "
style = "yellow"

[username]
format = "[$user](blue)"

[hostname]
ssh_symbol = " "
format = "@[$hostname]($style): "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
version_format = '${raw}'
format = '[$symbol($version(-$name))]($style)'

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
disabled = true
symbol = " "
version_format = '${raw}'
format = '[$symbol$version]($style)'

[custom.elixir]
symbol = " "
style = 'bold purple'
command = "$ASDF_DIR/shims/elixir --short-version"
format = '[$symbol$output]($style)'
when = "test -f mix.exs"

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
version_format = '${raw}'
format = '[$symbol($version)]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
