#!/usr/bin/env sh
#              _           _
#             | |         (_)
#  _   _  __ _| |__   __ _ _ _ __ ___
# | | | |/ _` | '_ \ / _` | | '__/ __|
# | |_| | (_| | |_) | (_| | | | | (__
#  \__, |\__,_|_.__/ \__,_|_|_|  \___|
#   __/ |
#  |___/

# general space settings
yabai -m config layout         bsp
yabai -m config top_padding    6
yabai -m config bottom_padding 6
yabai -m config left_padding   6
yabai -m config right_padding  6
yabai -m config window_gap     6

# Spaces
# yabai -m space 1 --label one
# yabai -m space 2 --label two
# yabai -m space 3 --label three
# yabai -m space 4 --label four
# yabai -m space 5 --label five

# float preferences
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
# yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^1Password 7$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add title="^Opening .*$" manage=off layer=above

# disable tiling for all windows
# yabai -m rule --add title=".*" manage=off
# Concept: allow for properly changing focus on displays without moving the mouse every time you focus a window, doesn't work.
# yabai -m rule --add app="^.*$" mouse_follows_focus=off

# global settings
yabai -m config status_bar                   off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd79921
yabai -m config window_border                off
# yabai -m config window_border_width          4
# yabai -m config normal_window_border_color   0xff282828
# yabai -m config active_window_border_color   0xffebdbb2
yabai -m config split_ratio                  0.4
yabai -m config auto_balance                 on

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config external_bar all:26:0

# echo "yabai configuration loaded.."

# Limelight
killall limelight &> /dev/null
/usr/local/bin/limelight &> /dev/null &
