return{

  -- {
  --   "mhanberg/output-panel.nvim",
  --   event = "VeryLazy",
  --   config = function()
  --     require("output_panel").setup()
  --   end
  -- }
  -- {
  --   "telescope.nvim",
  --   dependencies = {
  --   "otavioschwanck/telescope-alternate",
  --   event = { "BufReadPre", "BufNewFile" },
  --   config = function()
  --     require("telescope").load_extension('telescope-alternate')
  --   end,
  --   setup = function()

  --     local alternate = require("telescope-alternate")

  --     alternate.setup({
  --       mappings = {
  --         "lib/tiger_web/views/api/*_view.ex": {
  --           "type": "view",
  --           "related": [
  --             "lib/tiger_web/controllers/api/{}_controller.ex"
  --           ],
  --           "template": [
  --             "defmodule TigerWeb.API.{dirname|camelcase|capitalize|dot}.{basename|camelcase|capitalize}View do",
  --             "  @moduledoc false",
  --             "",
  --             "  use TigerWeb, :view",
  --             "end"
  --           ]
  --         },
  --         "lib/tiger_web/controllers/api/*_controller.ex": {
  --           "type": "controller",
  --           "alternate": "test/tiger_web/controllers/{basename}_controller_test.exs",
  --           "related": [
  --             "lib/tiger_web/views/api/{}_view.ex"
  --           ],
  --           "template": [
  --             "defmodule TigerWeb.API.{dirname|camelcase|capitalize|dot}.{basename|camelcase|capitalize}Controller do",
  --             "  @moduledoc false",
  --             "",
  --             "  use TigerWeb, :api_controller",
  --             "end"
  --           ]
  --         },
  --         "test/tiger_web/controllers/api/*_controller_test.exs": {
  --           "alternate": "lib/tiger_web/controllers/{basename}_controller.ex",
  --           "type": "test",
  --           "related": [
  --             "lib/tiger_web/views/api/{}_view.ex"
  --           ],
  --           "template": [
  --             "defmodule TigerWeb.API.{dirname|camelcase|capitalize|dot}.{basename|camelcase|capitalize}ControllerTest do",
  --             "  @moduledoc false",
  --             "",
  --             "  use TigerWeb.ConnCase, async: true",
  --             "end"
  --           ]
  --         },
  --         "lib/*.ex": {
  --           "alternate": "test/{}_test.exs",
  --           "type": "source",
  --           "template": [
  --             "defmodule {camelcase|capitalize|dot} do",
  --             "  @moduledoc \"\"\"",
  --             "",
  --             "  \"\"\"",
  --             "end"
  --           ]
  --         },
  --         "test/*_test.exs": {
  --           "alternate": "lib/{}.ex",
  --           "type": "test",
  --           "template": [
  --             "defmodule {camelcase|capitalize|dot}Test do",
  --             "  use Tiger.DataCase, async: true",
  --             "",
  --             "  alias {camelcase|capitalize|dot}",
  --             "end"
  --           ]
  --         }
  --       }
  --     })
  --   end
  --   }

  -- },
}
