[settings]
disable_tools = ['redis', 'postgres']
experimental = true

[tools]
# elixir = "latest"
# erlang = "latest"
# node = "latest"
# nodejs = "latest"
# usage = "latest"
# go = "latest"
# lua = "5.1.5"
