[settings]
disable_tools = ['redis', 'postgres']
experimental = true

[tools]
elixir = "latest"
erlang = "latest"
node = "latest"
nodejs = "latest"
rust = "latest"
usage = "latest"
go = "latest"
"cargo:eza" = "latest"
"cargo:bat" = "latest"
"cargo:ripgrep" = "latest"
